import './globals.css'

import ListCount from '@/components/ListCount'
import ListClient from '@/components/ListClient'
import Personal from '@/components/Personal'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import Loader from '@/components/Loader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          <div className="w-[220px] border-r bg-gray-100 py-8 px-4 h-screen">
            <Suspense fallback={<Loader/>}>
              {/* <ListCount/> */}
              <ListClient>
                <Personal/>
              </ListClient>
            </Suspense>
    
          </div>
          <div className="grow">
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
